---
sidebar: sidebar 
permalink: concept-azure-netapp-files.html 
keywords: azure netapp files, cost, price, features, azure netapp files features, anf, supported regions, azure regions, azure netapp files regions 
summary: 'Azure NetApp Files permet aux entreprises de migrer et d"exécuter leurs applications stratégiques, stratégiques ou stratégiques, gourmandes en performances et en latence, dans Azure sans remaniement pour le cloud.' 
---
= Découvrez Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure NetApp Files permet aux entreprises de migrer et d'exécuter leurs applications stratégiques, stratégiques ou stratégiques, gourmandes en performances et en latence, dans Azure sans remaniement pour le cloud.



== Caractéristiques

* La prise en charge de plusieurs protocoles permet d'exécuter les applications Linux et Windows de façon transparente dans Azure.
* Plusieurs tiers de performance permettent un alignement étroit avec les exigences de performances des charges de travail.
* Les certifications comme SAP HANA, le RGPD et HIPAA permettent la migration des workloads les plus exigeants vers Azure.




== Fonctions supplémentaires dans BlueXP

* Migrez des données NFS ou SMB vers Azure NetApp Files directement depuis BlueXP (anciennement Cloud Manager). Les migrations de données sont optimisées par le service Cloud Sync de NetApp.
+
https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["En savoir plus sur Cloud Sync"^]

* Avec la technologie d'intelligence artificielle (IA), Cloud Data Sense peut vous aider à comprendre le contexte des données et à identifier les données sensibles qui résident sur vos comptes Azure NetApp Files.
+
https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["Pour en savoir plus sur Cloud Data Sense"^]





== Le coût

https://azure.microsoft.com/pricing/details/netapp/["Voir la tarification Azure NetApp Files"^]

Notez que votre abonnement et la facturation sont gérés par le service Azure NetApp Files et non par BlueXP.



== Régions prises en charge

https://cloud.netapp.com/cloud-volumes-global-regions["Affichez les régions Azure prises en charge"^]



== Obtenir de l'aide

Pour tout problème de support technique lié à Azure NetApp Files, utilisez le portail Azure pour enregistrer une demande de support auprès de Microsoft. Sélectionnez votre abonnement Microsoft associé et sélectionnez le nom de service *Azure NetApp Files* sous *stockage*. Fournissez les informations restantes nécessaires pour créer votre demande d'assistance Microsoft.



== Liens connexes

* https://cloud.netapp.com/azure-netapp-files["Site web NetApp BlueXP : Azure NetApp Files"^]
* https://docs.microsoft.com/azure/azure-netapp-files/["Documentation Azure NetApp Files"^]
* https://docs.netapp.com/us-en/cloud-manager-sync/index.html["Documentation Cloud Sync"^]

